# Ex2 - Getting and Knowing your Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [2]:
from pathlib import Path
import pandas as pd


def data_path(filename):
    matches = list(Path.cwd().rglob(filename))
    return matches[0] if matches else filename

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/thieu1995/csv-files/main/data/pandas/chipotle.tsv).

source = data_path("chipotle.tsv")
if not Path(source).exists():
    source = "https://raw.githubusercontent.com/thieu1995/csv-files/main/data/pandas/chipotle.tsv"

chipo = pd.read_csv(source, sep="\t")

In [3]:
chipo = pd.read_csv("https://raw.githubusercontent.com/thieu1995/csv-files/main/data/pandas/chipotle.tsv", sep="\t")

### Step 4. See the first 10 entries

In [4]:
chipo.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

### Step 5. What is the number of observations in the dataset?

In [5]:
chipo.shape[0]

4622

In [6]:
chipo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB

### Step 6. What is the number of columns in the dataset?

In [7]:
chipo.shape[1]

5

### Step 7. Print the name of all the columns.

In [8]:
chipo.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

### Step 8. How is the dataset indexed?

In [9]:
chipo.index

RangeIndex(start=0, stop=4622, step=1)

### Step 9. Which was the most-ordered item?

In [10]:
most_ordered = chipo.groupby("item_name").quantity.sum().sort_values(ascending=False)
most_ordered.head(1)

item_name
Chicken Bowl    761
Name: quantity, dtype: int64

### Step 10. For the most-ordered item, how many items were ordered?

In [11]:
most_ordered.iloc[0]

np.int64(761)

### Step 11. What was the most ordered item in the choice_description column?

In [12]:
chipo.groupby("choice_description").quantity.sum().sort_values(ascending=False).head(1)

choice_description
[Diet Coke]    159
Name: quantity, dtype: int64

### Step 12. How many items were orderd in total?

In [13]:
chipo.quantity.sum()

np.int64(4972)

### Step 13. Turn the item price into a float

#### Step 13.a. Check the item price type

In [14]:
chipo.item_price.dtype

dtype('O')

#### Step 13.b. Create a lambda function and change the type of item price

In [15]:
chipo.item_price = chipo.item_price.str.replace("$", "", regex=False).astype(float)
chipo.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98

#### Step 13.c. Check the item price type

In [16]:
chipo.item_price.dtype

dtype('float64')

### Step 14. How much was the revenue for the period in the dataset?

In [17]:
revenue = (chipo.quantity * chipo.item_price).sum()
revenue

np.float64(39237.02)

### Step 15. How many orders were made in the period?

In [18]:
chipo.order_id.nunique()

1834

### Step 16. What is the average revenue amount per order?

In [19]:
order_revenue = chipo.groupby("order_id").apply(lambda order: (order.quantity * order.item_price).sum())
order_revenue.mean()

/tmp/ipykernel_12953/4058954102.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  order_revenue = chipo.groupby("order_id").apply(lambda order: (order.quantity * order.item_price).sum())

np.float64(21.39423118865867)

In [20]:
chipo["revenue"] = chipo.quantity * chipo.item_price
chipo.groupby("order_id").revenue.sum().mean()

np.float64(21.39423118865867)

### Step 17. How many different items are sold?

In [21]:
chipo.item_name.nunique()

50