# Iris

### Introduction:

This exercise may seem a little bit strange, but keep doing it.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data).

### Step 3. Assign it to a variable called iris

In [2]:
iris = pd.read_csv("iris.csv", header=None)

### Step 4. Create columns for the dataset

In [3]:
iris.columns = ["sepal_length", "sepal_width", "petal_length", "petal_width", "class"]
iris.head()

   sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

### Step 5.  Is there any missing value in the dataframe?

In [4]:
iris.isna().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
class           0
dtype: int64

### Step 6.  Lets set the values of the rows 10 to 29 of the column 'petal_length' to NaN

In [5]:
iris.loc[10:29, "petal_length"] = np.nan
iris.loc[10:29]

    sepal_length  sepal_width  petal_length  petal_width        class
10           5.4          3.7           NaN          0.2  Iris-setosa
11           4.8          3.4           NaN          0.2  Iris-setosa
12           4.8          3.0           NaN          0.1  Iris-setosa
13           4.3          3.0           NaN          0.1  Iris-setosa
14           5.8          4.0           NaN          0.2  Iris-setosa
15           5.7          4.4           NaN          0.4  Iris-setosa
16           5.4          3.9           NaN          0.4  Iris-setosa
17           5.1          3.5           NaN          0.3  Iris-setosa
18           5.7          3.8           NaN          0.3  Iris-setosa
19           5.1          3.8           NaN          0.3  Iris-setosa
20           5.4          3.4           NaN          0.2  Iris-setosa
21           5.1          3.7           NaN          0.4  Iris-setosa
22           4.6          3.6           NaN          0.2  Iris-setosa
23           5.1          3.3           NaN          0.5  Iris-setosa
24           4.8          3.4           NaN          0.2  Iris-setosa
25           5.0          3.0           NaN          0.2  Iris-setosa
26           5.0          3.4           NaN          0.4  Iris-setosa
27           5.2          3.5           NaN          0.2  Iris-setosa
28           5.2          3.4           NaN          0.2  Iris-setosa
29           4.7          3.2           NaN          0.2  Iris-setosa

### Step 7. Good, now lets substitute the NaN values to 1.0

In [6]:
iris.petal_length = iris.petal_length.fillna(1.0)
iris.loc[10:29]

    sepal_length  sepal_width  petal_length  petal_width        class
10           5.4          3.7           1.0          0.2  Iris-setosa
11           4.8          3.4           1.0          0.2  Iris-setosa
12           4.8          3.0           1.0          0.1  Iris-setosa
13           4.3          3.0           1.0          0.1  Iris-setosa
14           5.8          4.0           1.0          0.2  Iris-setosa
15           5.7          4.4           1.0          0.4  Iris-setosa
16           5.4          3.9           1.0          0.4  Iris-setosa
17           5.1          3.5           1.0          0.3  Iris-setosa
18           5.7          3.8           1.0          0.3  Iris-setosa
19           5.1          3.8           1.0          0.3  Iris-setosa
20           5.4          3.4           1.0          0.2  Iris-setosa
21           5.1          3.7           1.0          0.4  Iris-setosa
22           4.6          3.6           1.0          0.2  Iris-setosa
23           5.1          3.3           1.0          0.5  Iris-setosa
24           4.8          3.4           1.0          0.2  Iris-setosa
25           5.0          3.0           1.0          0.2  Iris-setosa
26           5.0          3.4           1.0          0.4  Iris-setosa
27           5.2          3.5           1.0          0.2  Iris-setosa
28           5.2          3.4           1.0          0.2  Iris-setosa
29           4.7          3.2           1.0          0.2  Iris-setosa

### Step 8. Now let's delete the column class

In [7]:
iris = iris.drop(columns="class")
iris.head()

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

### Step 9.  Set the first 3 rows as NaN

In [8]:
iris.iloc[:3] = np.nan
iris.head()

   sepal_length  sepal_width  petal_length  petal_width
0           NaN          NaN           NaN          NaN
1           NaN          NaN           NaN          NaN
2           NaN          NaN           NaN          NaN
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

### Step 10.  Delete the rows that have NaN

In [9]:
iris = iris.dropna()
iris.head()

   sepal_length  sepal_width  petal_length  petal_width
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2
5           5.4          3.9           1.7          0.4
6           4.6          3.4           1.4          0.3
7           5.0          3.4           1.5          0.2

### Step 11. Reset the index so it begins with 0 again

In [10]:
iris = iris.reset_index(drop=True)
iris.head()

   sepal_length  sepal_width  petal_length  petal_width
0           4.6          3.1           1.5          0.2
1           5.0          3.6           1.4          0.2
2           5.4          3.9           1.7          0.4
3           4.6          3.4           1.4          0.3
4           5.0          3.4           1.5          0.2

### BONUS: Create your own question and answer it.

In [11]:
iris.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    147.000000   147.000000    147.000000   147.000000
mean       5.862585     3.050340      3.741497     1.219048
std        0.824971     0.436263      1.840520     0.757278
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.500000     0.300000
50%        5.800000     3.000000      4.400000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000