# Pokemon

### Introduction:

This time you will create the data.



### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Create a data dictionary that looks like the DataFrame below

In [2]:
raw_data = {
    "name": ["Bulbasaur", "Charmander", "Squirtle", "Caterpie"],
    "type": ["grass", "fire", "water", "bug"],
    "hp": [45, 39, 44, 45],
    "evolution": ["Ivysaur", "Charmeleon", "Wartortle", "Metapod"],
    "pokedex": ["yes", "no", "yes", "no"],
}

### Step 3. Assign it to a variable called pokemon

In [3]:
pokemon = pd.DataFrame(raw_data)
pokemon

         name   type  hp   evolution pokedex
0   Bulbasaur  grass  45     Ivysaur     yes
1  Charmander   fire  39  Charmeleon      no
2    Squirtle  water  44   Wartortle     yes
3    Caterpie    bug  45     Metapod      no

### Step 4. Ops...it seems the DataFrame columns are in alphabetical order. Place  the order of the columns as name, type, hp, evolution, pokedex

In [4]:
pokemon = pokemon[["name", "type", "hp", "evolution", "pokedex"]]
pokemon

         name   type  hp   evolution pokedex
0   Bulbasaur  grass  45     Ivysaur     yes
1  Charmander   fire  39  Charmeleon      no
2    Squirtle  water  44   Wartortle     yes
3    Caterpie    bug  45     Metapod      no

### Step 5. Add another column called place, and insert what you have in mind.

In [5]:
pokemon["place"] = ["forest", "volcano", "lake", "garden"]
pokemon

         name   type  hp   evolution pokedex    place
0   Bulbasaur  grass  45     Ivysaur     yes   forest
1  Charmander   fire  39  Charmeleon      no  volcano
2    Squirtle  water  44   Wartortle     yes     lake
3    Caterpie    bug  45     Metapod      no   garden

### Step 6. Present the type of each column

In [6]:
pokemon.dtypes

name         object
type         object
hp            int64
evolution    object
pokedex      object
place        object
dtype: object

### BONUS: Create your own question and answer it.

In [7]:
pokemon.loc[pokemon.hp == pokemon.hp.max()]

        name   type  hp evolution pokedex   place
0  Bulbasaur  grass  45   Ivysaur     yes  forest
3   Caterpie    bug  45   Metapod      no  garden